hotel_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt import views as jwt_views

from frontend.api.views import api_homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls')),
    path('customers/', include('customers.urls')),
    path('rooms/', include('rooms.urls')),
    path('reservations/', include('reservations.urls')),
    path('analysis/', include('analysis.urls')),

    path('warehouse/', include('vendors.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('generic-expenses/', include('general_expenses.urls')),

    path('api/', api_homepage_view),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rooms/', include('rooms.api.urls')),
    path('api/customers', include('customers.api.urls')),

    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

reservations/urls.py
from django.urls import path

from .views import (HomepageView, ReservationListView, ReservationCreateView, ReservationUpdateView,
                    close_reservation_and_pay_view, ReservationDeleteView

                    )

from .action_views import (create_room_reservation_view, validate_customer_view, reservation_actions_view,
                           reservation_action_pay_view, recalculate_prices_view, action_remove_price_from_reservation,
                           change_room_and_check_availability_view, action_create_charge_from_reservarion,
                           create_new_payment_for_reservation_view, validate_create_or_delete_payment_for_reservation_view,
                           update_payment_view

                           )
from rooms.ajax_views import ajax_prices_modal_view

from .autocomplete_forms import CustomerAutocomplete

app_name = 'reservations'

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),

    path('create-reservation/', ReservationCreateView.as_view(), name='create_reservation'),
    path('reservation-list/', ReservationListView.as_view(), name='reservation_list'),
    path('update-reservation/<int:pk>/', ReservationUpdateView.as_view(), name='update_reservation'),
    path('close-and-pay-reservation/<int:pk>/', close_reservation_and_pay_view, name='close_and_pay_reservation'),
    path('actions/reservation-pay/<int:pk>/<slug:movement>/', reservation_action_pay_view, name='action_reservation_pay'),
    path('delete-reservation/<int:pk>/', ReservationDeleteView.as_view(), name='delete_reservation'),


    # action
    path('action/create-room/<int:pk>/', create_room_reservation_view, name='action-create-reservation'),
    path('action/validate-customer-form/', validate_customer_view, name='validate_customer'),
    path('action/validate-customer-form/', validate_customer_view, name='validate_customer'),
    path('action/reservation-quick-action/<int:pk>/<slug:slug>/', reservation_actions_view, name='reservation_actions'),
    path('action/re-calculate-prices/<int:pk>/', recalculate_prices_view, name='recalculate_prices'),
    path('action/add-remove-extra-prices/<int:pk>/<int:dk>/', action_remove_price_from_reservation, name='remove_extra_prices'),
    path('action/change-room-on-reservation/<int:pk>/<int:dk>/<str:price>/', change_room_and_check_availability_view, name='change_room_prices'),
    path('action/create-charge-from-reservation/<int:pk>/', action_create_charge_from_reservarion, name='action_charge_from_reservation'),
    path('action/create-payment-from-reservation/<int:pk>/', create_new_payment_for_reservation_view, name='create-payment-reservation'),
    path('action/update-payment-reservation/<int:pk>/<slug:action>/', validate_create_or_delete_payment_for_reservation_view, name='update-delete-payment-reservation'),
    path('actions/update-payment/<int:pk>/', update_payment_view, name='update-payment'),



    path('autocomplete/find-customer/', CustomerAutocomplete.as_view(), name='auto_customers'),

    path('ajax/price-modal/<int:pk>/', ajax_prices_modal_view, name='ajax_room_price_modal'),
]

rooms/urls.py
from django.urls import path

from .views import (RoomListView, RoomCreateView, RoomUpdateView, RoomDeleteView, RoomCardView)
from .actions_views import (room_price_create_view, room_price_edit_view, room_price_delete_view,
                            action_add_remove_room_from_card_view, room_price_add_remove_price_view,
                            room_charge_add_remove_price_view, room_charge_create_view

                            )

from .price_views import (RoomPriceListView, RoomPriceCreateView, RoomPriceUpdateView, RoomPriceDeleteView,
                          room_price_card_view
                          )
from .room_charges_view import RoomChargeListView, RoomChargeUpdateView, RoomChargeCreateView, RoomChargeDeleteView, room_charge_card_view

app_name = 'rooms'

urlpatterns = [
    path('list/', RoomListView.as_view(), name='list'),
    path('create/', RoomCreateView.as_view(), name='create'),
    path('update/<int:pk>/', RoomUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', RoomDeleteView.as_view(), name='delete'),
    path('card/<int:pk>/', RoomCardView.as_view(), name='card'),

    # actions views
    path('action/create-price/<int:pk>/', room_price_create_view, name='action_room_price'),
    path('room-price/edit/<int:pk>/', room_price_edit_view, name='action_room_price_edit'),
    path('room-price/delete/<int:pk>/', room_price_delete_view, name='action_room_price_delete'),
    path('action-room-card-add-remove/<int:pk>/<int:dk>/<str:action>/',
         action_add_remove_room_from_card_view, name='action_room_price_card_add_remove'),

    path('action/room-add-remove-price/<int:pk>/<int:dk>/<str:action>/', room_price_add_remove_price_view,
         name='room_price_add_remove'),

    path('action/charge-price/<int:pk>/', room_charge_create_view, name='action_room_charge'),
    path('action/charge-add-remove-price/<int:pk>/<int:dk>/<str:action>/', room_charge_add_remove_price_view,
         name='room_charge_add_remove'),

    # room_views
    path('room-price/list/', RoomPriceListView.as_view(), name='room_price_list'),
    path('room-price/create/', RoomPriceCreateView.as_view(), name='room_price_create'),
    path('room-price/update/<int:pk>/', RoomPriceUpdateView.as_view(), name='room_price_update'),
    path('room-price/delete-S/<int:pk>/', RoomPriceDeleteView.as_view(), name='room_price_delete'),
    path('room-price-card/<int:pk>/', room_price_card_view, name='room_price_card'),


    # room values

    path('room-charge/list/', RoomChargeListView.as_view(), name='room_charge_list'),
    path('room-charge/create/', RoomChargeCreateView.as_view(), name='room_charge_create'),
    path('room-charge/update/<int:pk>/', RoomChargeUpdateView.as_view(), name='room_charge_update'),
    path('room-charge/delete-S/<int:pk>/', RoomChargeDeleteView.as_view(), name='room_charge_delete'),
    path('room-charge-card/<int:pk>/', room_charge_card_view, name='room_charge_card'),





]

vendors/models.py
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django.shortcuts import reverse
from django.db.models.signals import post_delete
from django.dispatch import receiver

from tinymce.models import HTMLField
from decimal import Decimal
from frontend.models import PaymentMethod

from frontend.tools import initial_date

CURRENCY = settings.CURRENCY
TAXES_CHOICES = (
    ('a', 0),
    ('b', 13),
    ('c', 24)
)


class Vendor(models.Model):
    active = models.BooleanField(default=True, verbose_name='Ενεργό')
    title = models.CharField(max_length=200, unique=True, verbose_name='Εταιρία')
    owner = models.CharField(max_length=200, blank=True, verbose_name='Ιδιοκτήτης')
    afm = models.CharField(max_length=150, blank=True, verbose_name='ΑΦΜ')
    doy = models.CharField(max_length=150, blank=True, verbose_name='ΔΟΥ')
    phone = models.CharField(max_length=200, blank=True, verbose_name='Σταθερο Τηλεφωνο')
    cellphone = models.CharField(max_length=200, blank=True, verbose_name='Κινητό')
    email = models.EmailField(blank=True)
    site = models.URLField(blank=True, null=True)
    description = models.TextField(blank=True, null=True, verbose_name='Λεπτομεριες')
    address = models.CharField(max_length=240, blank=True, null=True, verbose_name='Διευθυνση')
    city = models.CharField(max_length=240, blank=True, null=True, verbose_name='Πολη')
    balance = models.DecimalField(decimal_places=2, max_digits=50, default=0.00, verbose_name='Υπόλοιπο')
    paid_value = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
    value = models.DecimalField(decimal_places=2, max_digits=50, default=0.00)
    taxes_modifier = models.CharField(max_length=1, choices=TAXES_CHOICES, default='c')

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):
        self.balance = self.value - self.paid_value
        self.title = self.title.upper()
        super().save(*args, **kwargs)

    def get_edit_url(self):
        return reverse('vendors:update', kwargs={'pk': self.id})

    def get_card_url(self):
        return reverse('vendors:vendor_card', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('vendors:delete', kwargs={'pk': self.id})

    def update_paid_value(self):
        qs = self.payments.all()
        value = qs.aggregate(Sum('value'))['value__sum'] if qs.exists() else 0
        self.paid_value = Decimal(value)
        self.save()

    def update_value(self):
        qs = self.invoices.all()
        value = qs.aggregate(Sum('final_value'))['final_value__sum'] if qs.exists() else 0
        self.value = Decimal(value)
        self.save()

    def tag_balance(self):
        return f'{self.balance} {CURRENCY}'
    tag_balance.short_description = 'Υπολοίπο'
    
    @staticmethod
    def filters_data(request, qs):
        search_name = request.GET.get('q', None)
        search_name_ = request.GET.get('search_name', None)
        vendor_name = request.GET.getlist('vendor_name', None)
        balance_name = request.GET.getlist('balance_name', [])
     
        qs = qs.filter(title__icontains=search_name_.upper()) if search_name_ else qs
        qs = qs.filter(title__icontains=search_name.upper()) if search_name else qs
        qs = qs.filter(balance__gt=0) if 'have_'in balance_name else qs.filter(balance_name__lte=0) \
            if 'not' in balance_name else qs
        qs = qs.filter(id__in=vendor_name) if vendor_name else qs
        return qs


class Employer(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=200, verbose_name='Ονομασια')
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='persons', verbose_name='Προμηθευτης')
    phone = models.CharField(max_length=10, blank=True, verbose_name='Τηλεφωνο')
    cellphone = models.CharField(max_length=10, blank=True, verbose_name='Κινητο')
    email = models.EmailField(blank=True)

    class Meta:
        ordering = ['title', ]

    def __str__(self):
        return self.title


class VendorBankingAccount(models.Model):
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE, related_name='banking_accounts', null=True, verbose_name='Τροπος Πληρωμής')
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, verbose_name='Προμηθευτής', related_name='bankings')
    name = models.CharField(max_length=150, blank=True, verbose_name='Ονομα Δικαιούχου')
    iban = models.CharField(max_length=150, blank=True, )
    code = models.CharField(max_length=200, blank=True, verbose_name='Αριθμός Λογαριασμού')

    def __str__(self):
        return f'{self.vendor.title} {self.payment_method.title}'

    def get_edit_url(self):
        return reverse('vendors:ajax_edit_banking_account', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('vendors:delete_banking_account_view', kwargs={'pk': self.id})


class Invoice(models.Model):
    date = models.DateField(verbose_name='Ημερομηνια')
    title = models.CharField(max_length=150, verbose_name='Αριθμος Τιμολογιου')
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.PROTECT, null=True, verbose_name='Τροπος Πληρωμης')
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='invoices', verbose_name='Προμηθευτης')
    value = models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Καθαρή Αξια')
    extra_value = models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Επιπλέον Αξία')
    final_value = models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξία', default=0.00)
    description = models.TextField(blank=True, verbose_name='Λεπτομεριες')

    class Meta:
        ordering = ['-date']

    def save(self, *args, **kwargs):
        self.final_value = self.value + self.extra_value
        print('here')
        super(Invoice, self).save(*args, **kwargs)
        if self.vendor:
            self.vendor.update_value()
     
    def __str__(self):
        return f'{self.title}'

    def tag_value(self):
        return f'{self.final_value} {CURRENCY}'

    @staticmethod
    def filters_data(request, qs):
        date_start, date_end, date_range = initial_date(request, 6)
        print('start', date_start, 'end', date_end)
        search_name = request.GET.get('search_name', None)
        qs = qs.filter(title__icontains=search_name) if search_name else qs
        if date_start and date_end:
            print('hitted!', date_end, date_start)
            qs = qs.filter(date__range=[date_start, date_end])
        print(qs.count())
        return qs


class Payment(models.Model):
    date = models.DateField(verbose_name='Ημερομηνία')
    title = models.CharField(max_length=150, verbose_name='Τίτλος')
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.PROTECT, null=True, verbose_name='Τροπος Πληρωμής')
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='payments', verbose_name='Προμηθευτής')
    value = models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξία')
    description = models.TextField(blank=True, verbose_name='Περιγραφή')

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f'{self.title}'

    def save(self,  *args, **kwargs):
        super().save(*args, **kwargs)
        if self.vendor:
            self.vendor.update_paid_value()

    def tag_value(self):
        return f'{self.value} {CURRENCY}'

    def filters_data(request, qs):
        date_start, date_end, date_range = initial_date(request, 6)
        if date_start and date_end:
            qs = qs.filter(date__range=[date_start, date_end])
        return qs

    # for reports
    
    @property
    def report_date(self):
        return self.date

    def report_expense_type(self):
        return f'Πληρωμη-{self.vendor}'

    def report_value(self):
        return self.value


class Note(models.Model):
    status = models.BooleanField(default=True, verbose_name='Κατάσταση')
    vendor_related = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='notes')
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    text = HTMLField(blank=True)

    def __str__(self):
        return f'{self.title}' if self.title else 'Σημειωση'

@receiver(post_delete, sender=Payment)
def update_vendor_on_delete(sender, instance, **kwargs):
    instance.vendor.update_paid_value()

@receiver(post_delete, sender=Invoice)
def update_vendor_invoice_on_delete(sender, instance, **kwargs):
    instance.vendor.update_value()
    
    

reservations/templates/print/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{{ instance.costumer }} | {{ instance.get_series_display }} | {{ instance.number }}</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
        <style>
            .my_p{
                padding-right: 3rem !important;
                padding-left: 3rem !important;
            }
            .bottom {
                position: absolute;
                bottom: 10px;
            }
            table {
                border: 2px ;
            }
        </style>
    </head>
    <body>
        <div class="container" style="height: 29.7cm;">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="row pb-5 p-5">
                            <div class="col-md-6">
                                <p class="font-weight-bold mb-4">{{ card_info.eponimia }}</p>
                                <p class="mb-1">{{ card_info.job }}</p>
                                <p class="mb-1">{{ card_info.city }}</p>
                                <p class="mb-1">ΑΦΜ: {{ card_info.afm }} ΔΟΥ: {{ card_info.doy }}</p>
                                <p class="mb-1">ΤΗΛΕΦΩΝΑ: {{ card_info.phone }}</p>
                                <br>
                            </div>
                            <div class="col-6"></div>
                                <div class="col-12">
                                     <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>ΕΙΔΟΣ ΠΑΡΑΣΤΑΤΙΚΟΥ</th>
                                            <th>ΑΡΙΘΜΟΣ</th>
                                            <th>ΗΜΕΡΟΜΗΝΙΑ</th>
                                            <th>ΩΡΑ</th>
                                            <th>ΣΕΙΡΑ</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ instance.get_order_type_display }}</td>
                                            <td>{{ instance.number }}</td>
                                            <td>{{ instance.date|date:"d/m/Y"}}</td>
                                            <td>{{ instance.date|date:"H:m"}}</td>
                                            <td>{{ instance.get_series_display }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                                </div>
                                <div class="col-md-6">
                                    <p class="font-weight-bold mb-4">Πληροφοριες Πελατη</p>
                                    <table class="table table-bordered table-sm">
                                        <tbody>
                                            <tr>
                                                <th>Επωνυμία</th>
                                                <td>{{ costumer.eponimia }}</td>
                                            </tr>
                                            <tr>
                                                <th>Επάγγελμα</th>
                                                <td>{{ costumer.job_description }}</td>
                                            </tr>
                                            <tr>
                                                <th>Διεύθυνση</th>
                                                <td>{{ costumer.address }}</td>
                                            </tr>
                                             <tr>
                                                <th>Πολη - ΤΚ</th>
                                                <td>{{ costumer.city }} {{ card_info.zipcode }}</td>
                                            </tr>
                                            <tr>
                                                <th>Α.Φ.Μ. - Δ.Ο.Υ</th>
                                                <td>{{ costumer.afm }} - {{ costumer.doy }}</td>
                                            </tr>

                                        </tbody>
                                    </table>
                                    {% comment %}
                                    <p class="mb-1">John Doe, Mrs Emma Downson</p>
                                    <p>Acme Inc</p>
                                    <p class="mb-1">Berlin, Germany</p>
                                    <p class="mb-1">6781 45P</p>
                                    {% endcomment %}
                                </div>
                                <div class="col-md-6 text-right">
                                     <br>
                                     <table class="table table-bordered table-sm">
                                        <tbody>
                                            <tr>
                                                <th>Σκοπός  Διακίνησης</th>
                                                <td>{{ instance.get_purpose_of_moving_display|default_if_none:'-' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Τόπος Αποστολής</th>
                                                <td>{{ costumer.loading_place }}</td>
                                            </tr>
                                            <tr>
                                                <th>Τόπος Προορισμού</th>
                                                <td>{{ costumer.destination }}</td>
                                            </tr>
                                            <tr>
                                                <th>Αριθμός Αυτοκινήτου</th>
                                                <td>{{ costumer.transport| default_if_none:"-" }}</td>
                                            </tr>
                                            <tr>
                                                <th>Τρόπος Πληρωμής</th>
                                                <td>{{ instance.get_payment_info_display }}</td>
                                            </tr>
                                        <tr>
                                                <th>Τηλέφωνο</th>
                                                <td>{% if costumer.phone %}{{ costumer.phone }} {% else %}  - {% endif %}</td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                                <div class="col-md-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="5" class="border-0 text-uppercase small font-weight-bold">ΠΕΡΙΓΡΑΦΗ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΜΜ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΠΟΣΟΤΗΤΑ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΤΙΜΗ <br> ΜΟΝΑΔΑΣ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΚΑΘΑΡΗ <br>ΑΞΙΑ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΕΚΠΤΩΣΗ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΣΥΝΟΛΙΚΗ<br> ΑΞΙΑ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΦΠΑ %</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for ele in instance.order_items.all %}
                                                <tr>
                                                    <td colspan="5">{{ ele.title }}</td>
                                                    <td>{{ ele.get_unit_display }}</td>
                                                    <td>{{ ele.qty }}</td>
                                                    <td>{{ ele.tag_value }}</td>
                                                    <td>{{ ele.tag_clean_value }}</td>
                                                    <td>{{ ele.tag_discount }} %</td>
                                                    <td>{{ ele.tag_total_value }}</td>
                                                    <td>{{ ele.get_taxes_modifier_display }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="row my_p">

                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div class="row bottom">
                <div class="col-2">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ΥΠΟΛΟΙΠΑ</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>ΠΡΟΗΓ.{{ instance.tag_old_balance }}</td>
                        </tr>
                        <tr>
                            <td>ΝΕΟ {{ instance.tag_new_balance }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-6">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ΚΑΘΑΡΗ ΑΞΙΑ</th>
                            <th>% ΦΠΑ</th>
                            <th>ΦΠΑ</th>
                            <th>ΣΥΝΟΛΙΚΗ ΑΞΙΑ</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for ele in different_taxes %}
                            <tr>
                                <td>{{ ele.total_clean }}</td>
                                <td>{{ ele.taxes_modifier }}</td>
                                <td>{{ ele.total_taxes }}</td>
                                <td>{{ ele.total }}</td>
                            </tr>
                        {% endfor %}
                         </tbody>
                    </table>
                </div>
                <div class="col-4">
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <th>ΚΑΘΑΡΗ ΑΞΙΑ</th>
                            <td>{{ instance.tag_clean_value }}</td>
                        </tr>
                        <tr>
                            <th>ΑΞΙΑ ΦΠΑ</th>
                            <td>{{ instance.tag_taxes_value }}</td>
                        </tr>
                        <tr>
                            <th>ΣΥΝΟΛΟ</th>
                            <td>{{ instance.tag_total_value }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-2">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ΣΥΝ. ΠΟΣΟΤΗΤΑ {{ total_qty }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
                <div class="col-5">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ΠΑΡΑΤΗΡΗΣΕΙΣ</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td style="height: 100px">{{ instance.notes|safe }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-3">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ΕΚΔΟΣΗ</th>
                                <th>ΠΑΡΑΔΟΣΗ</th>
                                <th>ΠΑΡΑΛΑΒΗ</th>
                            </tr>
                        </thead>
                        
                    </table>
                </div>
            </div>

        </div>
  </body>
</html>