analysis/urls.py
from django.urls import path

from .views import AnalysisHomepage, AnalysisIncomeView, AnalysisOutcomeView, CashRowView, BalanceSheetView, AnalysisReservationView

app_name='analysis'

urlpatterns = [
    path('homepage/', AnalysisHomepage.as_view(), name='homepage'),
    path('incomes/', AnalysisIncomeView.as_view(), name='income_analysis'),
    path('outcomes/', AnalysisOutcomeView.as_view(), name='outcome_analysis'),
    path('cash-row/', CashRowView.as_view(), name='cash_row'),
    path('balance-sheet/', BalanceSheetView.as_view(), name='balance_sheet'),
    path('reservations/analysis/', AnalysisReservationView.as_view(), name='reservation_analysis'),

    
]

hotel_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt import views as jwt_views

from frontend.api.views import api_homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls')),
    path('customers/', include('customers.urls')),
    path('rooms/', include('rooms.urls')),
    path('reservations/', include('reservations.urls')),
    path('analysis/', include('analysis.urls')),

    path('warehouse/', include('vendors.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('generic-expenses/', include('general_expenses.urls')),

    path('api/', api_homepage_view),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rooms/', include('rooms.api.urls')),
    path('api/customers', include('customers.api.urls')),

    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

rooms/urls.py
from django.urls import path

from .views import (RoomListView, RoomCreateView, RoomUpdateView, RoomDeleteView, RoomCardView)
from .actions_views import (room_price_create_view, room_price_edit_view, room_price_delete_view,
                            action_add_remove_room_from_card_view, room_price_add_remove_price_view,
                            room_charge_add_remove_price_view, room_charge_create_view

                            )

from .price_views import (RoomPriceListView, RoomPriceCreateView, RoomPriceUpdateView, RoomPriceDeleteView,
                          room_price_card_view
                          )
from .room_charges_view import RoomChargeListView, RoomChargeUpdateView, RoomChargeCreateView, RoomChargeDeleteView, room_charge_card_view

app_name = 'rooms'

urlpatterns = [
    path('list/', RoomListView.as_view(), name='list'),
    path('create/', RoomCreateView.as_view(), name='create'),
    path('update/<int:pk>/', RoomUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', RoomDeleteView.as_view(), name='delete'),
    path('card/<int:pk>/', RoomCardView.as_view(), name='card'),

    # actions views
    path('action/create-price/<int:pk>/', room_price_create_view, name='action_room_price'),
    path('room-price/edit/<int:pk>/', room_price_edit_view, name='action_room_price_edit'),
    path('room-price/delete/<int:pk>/', room_price_delete_view, name='action_room_price_delete'),
    path('action-room-card-add-remove/<int:pk>/<int:dk>/<str:action>/',
         action_add_remove_room_from_card_view, name='action_room_price_card_add_remove'),

    path('action/room-add-remove-price/<int:pk>/<int:dk>/<str:action>/', room_price_add_remove_price_view,
         name='room_price_add_remove'),

    path('action/charge-price/<int:pk>/', room_charge_create_view, name='action_room_charge'),
    path('action/charge-add-remove-price/<int:pk>/<int:dk>/<str:action>/', room_charge_add_remove_price_view,
         name='room_charge_add_remove'),

    # room_views
    path('room-price/list/', RoomPriceListView.as_view(), name='room_price_list'),
    path('room-price/create/', RoomPriceCreateView.as_view(), name='room_price_create'),
    path('room-price/update/<int:pk>/', RoomPriceUpdateView.as_view(), name='room_price_update'),
    path('room-price/delete-S/<int:pk>/', RoomPriceDeleteView.as_view(), name='room_price_delete'),
    path('room-price-card/<int:pk>/', room_price_card_view, name='room_price_card'),


    # room values

    path('room-charge/list/', RoomChargeListView.as_view(), name='room_charge_list'),
    path('room-charge/create/', RoomChargeCreateView.as_view(), name='room_charge_create'),
    path('room-charge/update/<int:pk>/', RoomChargeUpdateView.as_view(), name='room_charge_update'),
    path('room-charge/delete-S/<int:pk>/', RoomChargeDeleteView.as_view(), name='room_charge_delete'),
    path('room-charge-card/<int:pk>/', room_charge_card_view, name='room_charge_card'),





]

analysis/models.py
from django.db import models

# Create your models here.

analysis/views.py
from django.db.models import Sum, FloatField, F, Count, Avg
from django.db.models.functions import TruncMonth
from django.shortcuts import  reverse
from django.utils.encoding import force_text
from django.views.generic import ListView, TemplateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings


from operator import attrgetter
from itertools import chain

from customers.models import CustomerPayment
from payroll.models import Bill, Payroll
from vendors.models import Payment, Invoice
from general_expenses.models import GeneralExpense
from .tools import sort_months

from reservations.models import Reservation, SOURCES


@method_decorator(staff_member_required, name='dispatch')
class AnalysisHomepage(TemplateView):
    template_name = 'analysis/homepage.html'


@method_decorator(staff_member_required, name='dispatch')
class AnalysisIncomeView(ListView):
    model = CustomerPayment
    template_name = 'analysis/analysis_incomes.html'
    paginate_by = 100

    def get_queryset(self):
        qs = CustomerPayment.objects.all()
        # qs = CustomerPayment.filters_data(self.request, qs)
        return qs

    def get_context_data(self,  **kwargs):
        context = super().get_context_data(**kwargs)
        date_filter, currency = True, settings.CURRENCY
        back_url = reverse('analysis:homepage')
        # total_z = self.object_list.aggregate(Sum('sum_z'))['sum_z__sum'] if self.object_list.exists() else 0
        # total_pos = self.object_list.aggregate(Sum('pos'))['pos__sum'] if self.object_list.exists() else 0
        # total_cash = total_z - total_pos
        # total_order = self.object_list.aggregate(Sum('order_cost'))['order_cost__sum'] if self.object_list.exists() else 0
        total = self.object_list.aggregate(Sum('value'))['value__sum'] if self.object_list.exists() else 0
        # invoices_per_month = invoices.annotate(month=TruncMonth('date')).values('month').annotate(
        #     total=Sum('final_value')).values('month', 'total').order_by('month')
        analysis_per_month = self.object_list.annotate(month=TruncMonth('date')).values('month').annotate(
            total=Sum('value')).values('month', 'total').order_by('month')

        '''
        analysis_z_per_month = self.object_list.annotate(month=TruncMonth('date')).values('month').annotate(
            total=Sum('sum_z')).values('month', 'total').order_by('month')
        analysis_pos_per_month = self.object_list.annotate(month=TruncMonth('date')).values('month').annotate(
            total=Sum('pos')).values('month', 'total').order_by('month')
        analysis_cash_per_month = self.object_list.annotate(month=TruncMonth('date')).values('month').annotate(
            total=Sum('cash')).values('month', 'total').order_by('month')
        '''
        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class AnalysisReservationView(TemplateView):
    template_name = 'analysis/reservation_analysis.html'

    def get_context_data(self, **kwargs):
        context = super(AnalysisReservationView, self).get_context_data(**kwargs)
        context['back_url'] = reverse('analysis:homepage')
        qs = Reservation.my_query.filters_data(self.request)

        incomes = qs.filter(isDone=True, isCancel=False)
        qs_analysis = incomes.values('source').annotate(total=Sum('final_value'),
                                                        count_sum=Count('final_value'),
                                                        value=Sum('value'),
                                                        average=Avg('final_value')
                                                        ).order_by('total')

        sources = dict(Reservation._meta.get_field('source').flatchoices)
        for ele in qs_analysis:
            ele['source'] = force_text(sources[ele['source']], strings_only=True)

        total = qs.aggregate(Sum('final_value'))['final_value__sum'] if qs.exists() else 0
        isDoneQs = qs.filter(isDone=True)
        isActiveQs = qs.filter(isDone=False, isCancel=False)

        isDoneTotal = isDoneQs.aggregate(Sum('final_value'))['final_value__sum'] if isDoneQs.exists() else 0
        isActiveTotal = isActiveQs.aggregate(Sum('final_value'))['final_value__sum'] if isActiveQs.exists() else 0
        isDonePerMonth = isDoneQs.annotate(month=TruncMonth('check_out')).values('month').annotate(total=Sum('final_value')).values('month', 'total').order_by('month')
        isDonePerRoom = isDoneQs.values('room__title').annotate(
            total=Sum('final_value'),
            days=Sum('days'),
            count_sum=Count('final_value'),
            value=Sum('value'),
            average=Avg('final_value')
        ).order_by('total')


        #bills.annotate(month=TruncMonth('date_expired')).values('month').annotate(
          # total=Sum('final_value')).values('month', 'total').order_by('month')
        context['qs_analysis'] = qs_analysis
        context['isDoneTotal'] = isDoneTotal
        context['isActiveTotal'] = isActiveTotal
        context['isDonePerMonth'] = isDonePerMonth
        context['isDonePerRoom'] = isDonePerRoom
        context['date_filter'] = True
        return context


@method_decorator(staff_member_required, name='dispatch')
class AnalysisOutcomeView(TemplateView):
    template_name = 'analysis/analysis_outcome.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = settings.CURRENCY
        back_url = reverse('analysis:homepage')
        date_filter = True
        bills = Bill.filters_data(self.request, Bill.objects.all())
        payrolls = Payroll.filters_data(self.request, Payroll.objects.all())
        invoices = Invoice.filters_data(self.request, Invoice.objects.all())
        generic_expenses = GeneralExpense.filters_data(self.request, GeneralExpense.objects.all())
        generic_expenses_analysis = generic_expenses.values('category__title').annotate(total=Sum('value')).order_by('-total')
        generic_expenses_analysis_per_month = generic_expenses.annotate(month=TruncMonth('date')).values('month'). \
            annotate(total=Sum('value')).values('month', 'total').order_by('month')

        total_bills = bills.aggregate(Sum('final_value'))['final_value__sum'] if bills else 0
        analysis_bills = bills.values('category__title').annotate(total=Sum('final_value')).order_by('-total')
        analysis_bills_per_month = bills.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('final_value')).values('month', 'total').order_by('month')

        total_payroll = payrolls.aggregate(Sum('final_value'))['final_value__sum'] if payrolls else 0
        total_invoices = invoices.aggregate(Sum('final_value'))['final_value__sum'] if invoices else 0
        total_generic = generic_expenses.aggregate(Sum('value'))['value__sum'] if generic_expenses else 0
        total_expenses = total_bills + total_payroll + total_invoices + total_generic
        analysis_invoices = invoices.values('vendor__title').annotate(total=Sum('final_value')).order_by('-total')
        analysis_invoices_per_month = invoices.annotate(month=TruncMonth('date')).values('month').annotate(total=Sum('final_value')).values('month', 'total').order_by('month')
        payroll_analysis = payrolls.values('person__title').annotate(total=Sum('final_value')).order_by('-total')
        payroll_analysis_per_month = payrolls.annotate(month=TruncMonth('date_expired')).values('month').\
            annotate(total=Sum('final_value')).values('month', 'total').order_by('month')

        # get unique months
        months = sort_months([analysis_invoices_per_month, analysis_bills_per_month, payroll_analysis_per_month, generic_expenses_analysis_per_month])

        result_per_months = []
        for month in months:
            data = {
                'month': month,
                'total': 0
            }
            # data['invoice'] = ele['total'] for ele in analysis_invoices_per_month if ele['month'] == month else 0
            for ele in analysis_invoices_per_month:
                if ele['month'] == month:
                    data['invoice'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in analysis_bills_per_month:
                if ele['month'] == month:
                    data['bills'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in payroll_analysis_per_month:
                if ele['month'] == month:
                    data['payroll'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in generic_expenses_analysis_per_month:
                if ele['month'] == month:
                    data['generic'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            data['invoice'] = data['invoice'] if 'invoice' in data.keys() else 0
            data['bills'] = data['bills'] if 'bills' in data.keys() else 0
            data['payroll'] = data['payroll'] if 'payroll' in data.keys() else 0
            data['generic'] = data['generic'] if 'generic' in data.keys() else 0
            result_per_months.append(data)

        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CashRowView(TemplateView):
    template_name = 'analysis/cash_row.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = settings.CURRENCY
        back_url = reverse('analysis:homepage')
        incomes = CustomerPayment.filters_data(self.request, CustomerPayment.objects.all()).order_by('date_expired')
        total_z = incomes.aggregate(Sum('sum_z'))['sum_z__sum'] if incomes.exists() else 0

analysis/templates/analysis/analysis_incomes.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Συνολική Εικόνα  ==> <span style="color: green"> {{ total }} {{ currency }} </span></h4>
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Filters
                        </a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                        <a href="{{ back_url }}" class="btn btn-warning pull-right">Επιστροφη</a>
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="collapseExample">
                            <form method="get" class="form">
                                 <div class="row">
                                      {% include 'filters/my_filters.html' %}
                                 </div>
                                 <button type="submit" class="btn btn-"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                    <div class='row'>
                        <div class='col-md-4'>
                            <canvas id="totalChart" width="400" height="400"></canvas>
                        </div>
                         <div class='col-md-8' >
                            <canvas id="lineChart" width="400" height="400"></canvas>
                        </div>
                    </div>
                    
                </h4>
                 
                    
              </div>
              <div class="card-body">
                <div class='row'>
                    <div class='col-6'>
                        <h4>Αναλυση ανα μηνα </h4>
                        <table class='table table-bordered'>
                            <thead>
                                <tr>
                                    <th>Ημερομηνια</th>
                                    <th>Κερδη</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in analysis_per_month %}
                                   <tr>
                                        <td>{{ ele.month.month }}/{{ ele.month.year }}</td>
                                        <td>{{ ele.total }}</td>
                                   </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class='col-6'>
                        <h4>Αναλυση ανα κατηγορια</h4>
                        <table class='table table-bordered'>
                            <thead>
                                <tr>
                                    <th>Ειδος</th>
                                    <th>Κερδη</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td class='table-success'>Συνολο</td>
                                    <td class='table-success'>{{ total }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-10">
                        <h4>Δεδομενα</h4>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Ημερομηνια</th>
                                    <th>Πελάτης</th>
                                    <th>ΤΡΟΠΟΣ ΠΛΗΡΩΜΗΣ</th>
                                    <th>ΠΟΣΟ</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for income in object_list %}
                                    <tr>
                                        <td>{{ income.date }}</td>
                                        <td>{{ income.customer }}</td>
                                        <td>{{ income.payment_type }}</td>
                                        <td>{{ income.value }}</td>

                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row" id="modal_area">

        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js" integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
    <script>
var ctx = document.getElementById('totalChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Συνολο', 'Συνολο Ζ', 'Συνολο POS', 'Mετρητα', 'Συνολο Τιμ.'],
        datasets: [{
            label: '# Σε Ευρω',
            data: [{{ total }}, {{ total_z }}, {{ total_pos }}, {{ total_cash }}, {{ total_order }}],
            backgroundColor: [
                'green',
                'blue',
                'red',
                'yellow',
                'purple'
                
            ],
            borderColor: [
                'green',
                'blue',
                'red',
                'yellow',
                'purple'
                
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

<script>
var ctx = document.getElementById('lineChart');
var myChart = new Chart(ctx, {
    type: 'line',

    data: {
        labels: [{% for ele in analysis_per_month %} {% if forloop.last %} '{{ ele.month }}'{% else %} '{{ele.month}}', {% endif %} {% endfor %}],
        datasets: [
            {
				label: 'Εσοδα',
				backgroundColor: 'green',
				borderColor: 'green',
				fill: false,
				data:[{% for ele in analysis_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			}
            ]

		},
    options: {
        maintainAspectRatio: false,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});

</script>
{% endblock %}

analysis/templates/analysis/home.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h4>Analysis - Filters</h4>
                    </div>
                    <div class="card-body">
                        <form method="get" class="form">

                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> </button>
                        </form>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4>ΕΣΟΔΑ ΠΕΡΙΟΔΟΥ ==> {{ total_payments }}</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>ΤΡΟΠΟΣ ΠΛΗΡΩΜΗΣ</th>
                                    <th>ΑΡΙΘΜΟΣ ΠΛΗΡΩΜΩΝ</th>
                                    <th>ΕΣΟΔΑ</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in payment_analysis %}
                                    <tr>
                                        <td>{{ ele.payment_type }}</td>
                                        <td>{{ ele.count }}</td>
                                        <td>{{ ele.total }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'homepage' %}" class="btn btn-warning">ΕΠΙΣΤΡΟΦΗ</a>
                    </div>
                    <div class="card-body">
                        <h4>ΠΟΣΟΣΤΑ ΚΡΑΤΗΣΕΩΝ</h4>
                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th>ΣΥΝΟΛΙΚΕΣ ΚΡΑΤΗΣΕΙΣ</th>
                                    <td>{{ reservations_percent.total_count }}</td>
                                </tr>
                                <tr>
                                    <th>ΟΛΟΚΛΗΡΩΜΕΝΕΣ</th>
                                    <td>{{ reservations_percent.isDone }}</td>
                                </tr>
                                <tr>
                                    <th>ΑΚΥΡΩΜΕΝΕΣ</th>
                                    <td>{{ reservations_percent.isCancel }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4>ΣΥΝΟΛΑ</h4>
                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th>ΣΥΝΟΛΑ ΚΡΑΤΗΣΕΩΝ</th>
                                    <td>{{ reservations_percent.total }}</td>
                                </tr>
                                <tr>
                                    <th></th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th></th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th></th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4>ΠΗΓΕΣ</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>ΠΗΓΗ</th>
                                    <th>ΑΡΙΘΜΟΣ ΚΡΑΤΗΣΕΩΝ</th>
                                    <th>ΑΞΙΑ</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in source_analysis %}
                                    <tr>
                                        <td>{{ ele.source }}</td>
                                        <td>{{ ele.count }}</td>
                                        <td>{{ ele.total }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

analysis/templates/analysis/homepage.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Εσοδα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:income_analysis' %}" class="btn btn-success">Αναλυση Εσοδων</a>
                        {% comment %}<a href="{% url 'analysis:store_inventory' %}" class="btn btn-info pull-right">Απογραφη</a> {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Εξοδα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:outcome_analysis' %}" class="btn btn-danger">Αναλυση Εξόδων</a>
                        <a href="{% url 'analysis:reservation_analysis' %}" class="btn btn-success">Αναλυση Κρατησεων</a>
                    </div>
                </div>
            </div>

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Ισολογισμος</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:balance_sheet' %}" class="btn btn-warning">Αναλυση Εσοδων - Εξοδων</a>
                        {% comment %}<a href="{% url 'analysis:cash_row' %}" class="btn btn-info pull-right">Ταμειακη Ροη</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

analysis/templates/analysis/store_inventory.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <h2>Απογραφη</h2>
                            <h4>Συνολο Αποθηκης ==> {{ products_total.total }} €</h4>
                        </div>
                        <div class="card-body">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for ele in vendor_products %}
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            {% if ele.taxes_modifier == 'b' %} ΦΠΑ 13% {% endif %}
                            {% if  ele.taxes_modifier == 'c' %} ΦΠΑ 24% {% endif %}
                            {% if  ele.taxes_modifier == 'a' %} ΦΠΑ 0% {% endif %}

                        </div>
                        <div class="card-body">
                            ΣΥΝΟΛΟ... {{ ele.total }} €
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12">
                <div class="card">
                    <div class="card-header">Κατεβασμα Αρχείου</div>
                    <div class="card-body">
                            <button class="btn btn-info"><i class="fa fa-download"></i> Kατεβασμα.</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}