general_expenses/urls.py
from django.urls import path

from .views import (GenericExpensesListView, GeneralExpenseCreateView, GeneralExpenseUpdateView, delete_generic_expense_view,
                    GenericExpensesCategoryListView, GeneralExpenseCategoryUpdateView, GeneralExpenseCategoryCreateView, delete_generic_category_expense_view,
                    pay_expense_view
                    )

app_name = 'generic_expenses'

urlpatterns = [
    path('list/', GenericExpensesListView.as_view(), name='list'),
    path('update/<int:pk>/', GeneralExpenseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_generic_expense_view, name='delete'),
    path('create/', GeneralExpenseCreateView.as_view(), name='create'),
    path('pay/<int:pk>/', pay_expense_view, name='pay_expense'),

    path('category/list/', GenericExpensesCategoryListView.as_view(), name='category_list'),
    path('category/update/<int:pk>/', GeneralExpenseCategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', delete_generic_category_expense_view, name='category_delete'),
    path('category/create/', GeneralExpenseCategoryCreateView.as_view(), name='category_create'),

]

hotel_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt import views as jwt_views

from frontend.api.views import api_homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls')),
    path('customers/', include('customers.urls')),
    path('rooms/', include('rooms.urls')),
    path('reservations/', include('reservations.urls')),
    path('analysis/', include('analysis.urls')),

    path('warehouse/', include('vendors.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('generic-expenses/', include('general_expenses.urls')),

    path('api/', api_homepage_view),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rooms/', include('rooms.api.urls')),
    path('api/customers', include('customers.api.urls')),

    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

rooms/urls.py
from django.urls import path

from .views import (RoomListView, RoomCreateView, RoomUpdateView, RoomDeleteView, RoomCardView)
from .actions_views import (room_price_create_view, room_price_edit_view, room_price_delete_view,
                            action_add_remove_room_from_card_view, room_price_add_remove_price_view,
                            room_charge_add_remove_price_view, room_charge_create_view

                            )

from .price_views import (RoomPriceListView, RoomPriceCreateView, RoomPriceUpdateView, RoomPriceDeleteView,
                          room_price_card_view
                          )
from .room_charges_view import RoomChargeListView, RoomChargeUpdateView, RoomChargeCreateView, RoomChargeDeleteView, room_charge_card_view

app_name = 'rooms'

urlpatterns = [
    path('list/', RoomListView.as_view(), name='list'),
    path('create/', RoomCreateView.as_view(), name='create'),
    path('update/<int:pk>/', RoomUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', RoomDeleteView.as_view(), name='delete'),
    path('card/<int:pk>/', RoomCardView.as_view(), name='card'),

    # actions views
    path('action/create-price/<int:pk>/', room_price_create_view, name='action_room_price'),
    path('room-price/edit/<int:pk>/', room_price_edit_view, name='action_room_price_edit'),
    path('room-price/delete/<int:pk>/', room_price_delete_view, name='action_room_price_delete'),
    path('action-room-card-add-remove/<int:pk>/<int:dk>/<str:action>/',
         action_add_remove_room_from_card_view, name='action_room_price_card_add_remove'),

    path('action/room-add-remove-price/<int:pk>/<int:dk>/<str:action>/', room_price_add_remove_price_view,
         name='room_price_add_remove'),

    path('action/charge-price/<int:pk>/', room_charge_create_view, name='action_room_charge'),
    path('action/charge-add-remove-price/<int:pk>/<int:dk>/<str:action>/', room_charge_add_remove_price_view,
         name='room_charge_add_remove'),

    # room_views
    path('room-price/list/', RoomPriceListView.as_view(), name='room_price_list'),
    path('room-price/create/', RoomPriceCreateView.as_view(), name='room_price_create'),
    path('room-price/update/<int:pk>/', RoomPriceUpdateView.as_view(), name='room_price_update'),
    path('room-price/delete-S/<int:pk>/', RoomPriceDeleteView.as_view(), name='room_price_delete'),
    path('room-price-card/<int:pk>/', room_price_card_view, name='room_price_card'),


    # room values

    path('room-charge/list/', RoomChargeListView.as_view(), name='room_charge_list'),
    path('room-charge/create/', RoomChargeCreateView.as_view(), name='room_charge_create'),
    path('room-charge/update/<int:pk>/', RoomChargeUpdateView.as_view(), name='room_charge_update'),
    path('room-charge/delete-S/<int:pk>/', RoomChargeDeleteView.as_view(), name='room_charge_delete'),
    path('room-charge-card/<int:pk>/', room_charge_card_view, name='room_charge_card'),





]

vendors/urls.py
from django.urls import path
from .views import (HomepageView, VendorListView, CreateVendorView, UpdateVendorView, delete_vendor_view,
                    VendorNotesView, delete_note_view, NoteUpdateView
                    )

from .action_views import (validate_invoice_form_view, validate_employer_view,
                           validate_payment_form_view, validate_invoice_edit_form_view, delete_invoice_view, 
                           delete_payment_view, validate_payment_edit_form_view, validate_employer_edit_view,
                           delete_employer_view, validate_create_banking_account_view, validate_edit_banking_account_view, delete_banking_account_view,
                           validate_note_creation_view

               )
from .ajax_views import (ajax_invoice_modal_view, ajax_invoice_modal_view, 
                         ajax_employer_edit_modal_view, ajax_banking_account_create_modal_view, ajax_banking_account_edit_modal_view, 
                         ajax_payment_edit_modal_view, ajax_calculate_vendors_balance_view,
                         )


app_name = 'vendors'


urlpatterns = [
    path('home/', HomepageView.as_view(), name='home'),
    path('list/', VendorListView.as_view(), name='list'),
    path('create/', CreateVendorView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateVendorView.as_view(), name='update'),
    path('delete/vendor/<int:pk>/', delete_vendor_view, name='delete'),




    #  notes
    path('notes/<int:pk>/', VendorNotesView.as_view(), name='notes'),
    path('notes/validate-creation/<int:pk>/', validate_note_creation_view, name='note_create'),
    path('notes/update/<int:pk>/', NoteUpdateView.as_view(), name='note_update'),
    
    path('notes/delete/<int:pk>/', delete_note_view, name='note_delete'),
    
    path('actions/validate-invoice-form/<int:pk>/', validate_invoice_form_view, name='validate_invoice_view'),
    path('actions/validate-payment-form/<int:pk>/', validate_payment_form_view, name='validate_payment_view'),
    path('actions/validate-employer-form/<int:pk>/', validate_employer_view, name='validate_employer_view'),


    path('ajax/invoice-modal/<int:pk>/', ajax_invoice_modal_view, name='ajax_invoice_modal'),
    path('actions/validate-invoice-edit-form/<int:pk>/', validate_invoice_edit_form_view, name='validate_invoice_edit_view'),
    path('actions/invoice-delete/<int:pk>/', delete_invoice_view, name='action_delete_invoice'),

    path('ajax/payment-modal/<int:pk>/', ajax_payment_edit_modal_view, name='ajax_payment_modal'),
    path('actions/validate-payment-edit-form/<int:pk>/', validate_payment_edit_form_view, name='validate_payment_edit_view'),
    path('actions/payment-delete/<int:pk>/', delete_payment_view, name='action_delete_payment'),

    #  employer links
    path('actions/validate-employer-edit-form/<int:pk>/', validate_employer_edit_view, name='validate_employer_edit_view'),
    path('actions/employer-delete/<int:pk>/', delete_employer_view, name='action_delete_employer'),
    path('ajax/employer-modal/<int:pk>/', ajax_employer_edit_modal_view, name='ajax_employer_modal'),

    # banking accounts
    path('ajax/modal/banking-account/<int:pk>/', ajax_banking_account_create_modal_view, name='ajax_create_banking_account'),
    path('ajax/modal/banking-account-edit/<int:pk>/', ajax_banking_account_edit_modal_view, name='ajax_edit_banking_account'),
    path('validate/banking-account-create/<int:pk>/', validate_create_banking_account_view, name='validate_create_banking_account'),
    path('validate/banking_account-edit/<int:pk>/', validate_edit_banking_account_view, name='validate_edit_banking_account'),
    path('banking-account-delete/<int:pk>/', delete_banking_account_view, name='delete_account_banking_view'),





    ]

vendors/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from dal import autocomplete

from .models import Vendor, Invoice, Payment, Vendor, Employer, VendorBankingAccount, Note, TAXES_CHOICES



class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VendorForm(BaseForm, forms.ModelForm):
    site = forms.URLField(widget=forms.TextInput(), required=False)

    class Meta:
        model = Vendor
        fields = ['active', 'title', 'owner', 'afm', 'doy', 'phone', 'cellphone', 'address', 'email', 'site', 'taxes_modifier']

    def clean_site(self):
        data = self.cleaned_data.get('site', None)
        if data:
            if not 'http' in data:
                data = 'https://'+ data
        return data


class InvoiceVendorDetailForm(BaseForm, forms.ModelForm):
    vendor = forms.ModelChoiceField(queryset=Vendor.objects.all(), widget=forms.HiddenInput())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=True, label='Ημερομηνία')

    class Meta:
        model = Invoice
        fields = ['date', 'title', 'vendor', 'value', 'extra_value', 'payment_method', 'description']


class InvoiceForm(BaseForm, forms.ModelForm):
    vendor = forms.ModelChoiceField(queryset=Vendor.objects.all(), widget=forms.HiddenInput())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=True, label='Ημερομηνία')

    class Meta:
        model = Invoice
        fields = '__all__'


class PaymentForm(BaseForm, forms.ModelForm):
    vendor = forms.ModelChoiceField(queryset=Vendor.objects.all(), widget=forms.HiddenInput())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=True)
    
    class Meta:
        model = Payment
        fields = '__all__'


class EmployerForm(BaseForm, forms.ModelForm):
    vendor = forms.ModelChoiceField(queryset=Vendor.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = Employer
        fields = '__all__'


class VendorBankingAccountForm(BaseForm, forms.ModelForm):
    vendor = forms.ModelChoiceField(queryset=Vendor.objects.all(), widget=forms.HiddenInput())
    
    class Meta:
        model = VendorBankingAccount
        fields = '__all__'


class NoteForm(BaseForm, forms.ModelForm):
    vendor_related = forms.ModelChoiceField(queryset=Vendor.objects.all(), widget=forms.HiddenInput())
    text = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 200}))
    
    class Meta:
        model = Note
        fields = ['status', 'title', 'text', 'vendor_related']

class CopyProductToNewVendor(BaseForm):
    vendor = forms.ModelChoiceField(queryset=Vendor.objects.all(), label='Προμηθευτής')
    value = forms.DecimalField(required=True)
    discount = forms.IntegerField(required=True)
    added_value = forms.DecimalField(required=True)



    

vendors/views.py
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect

from django.contrib import messages
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse


from django_tables2 import RequestConfig
from .tables import VendorTable

from .models import Vendor, Note, Invoice
from .forms import VendorForm, InvoiceVendorDetailForm, EmployerForm, PaymentForm, NoteForm, Payment


@method_decorator(staff_member_required, name='dispatch')
class HomepageView(TemplateView):
    template_name = 'vendors/homepage.html'


@method_decorator(staff_member_required, name='dispatch')
class VendorListView(ListView):
    model = Vendor
    template_name = 'list_view.html'
    paginate_by = 25

    def get_queryset(self):
        qs = Vendor.objects.all()
        qs = Vendor.filters_data(self.request, qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs_table = VendorTable(self.object_list)
        RequestConfig(self.request, paginate={'per_page': self.paginate_by}).configure(qs_table)
        queryset_table = qs_table
        create_url = reverse('vendors:create')
        page_title, back_url = 'Προμηθευτές', reverse('vendors:home')
        # report_button, report_url = True, reverse('vendors:ajax_vendors_balance')
        balance_filter, search_filter = [True]*2
        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CreateVendorView(CreateView):
    template_name = 'form_view.html'
    model = Vendor
    form_class = VendorForm

    def get_initial(self):
        initial = super().get_initial()
        # initial['site'] = 'http://'
        return initial

    def get_success_url(self):
        return self.new_object.get_edit_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"], context['back_url'],  = 'Δημιουργια Προμηθευτη', reverse('vendors:list')

        return context

    def form_valid(self, form):
        self.new_object = form.save()
        new_vendor = form.cleaned_data['title']
        messages.success(self.request, f'Ο Προμηθευτής {new_vendor} δημιουργήθηκε.')
        return super().form_valid(form)
    

@method_decorator(staff_member_required, name='dispatch')
class UpdateVendorView(UpdateView):
    model = Vendor
    template_name = 'vendors/update_vendor.html'
    form_class = VendorForm

    def get_success_url(self):
        return self.object.get_edit_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['invoice_form'] = InvoiceVendorDetailForm(initial={'vendor': self.object})
        context['payment_form'] = PaymentForm(initial={'vendor': self.object})
        context['employer_form'] = EmployerForm(initial={'vendor': self.object})
        context['page_title'] = f'{self.object.title}'
        context['notes'] = Note.objects.filter(vendor_related=self.object, status=True)
        context['invoices'] = Invoice.filters_data(self.request, self.object.invoices.all())
        context['payments'] = Payment.filters_data(self.request, self.object.payments.all())
        context['action_url'] = reverse('vendors:list')
        return context
    

@staff_member_required
def delete_vendor_view(request, pk):
    instance = get_object_or_404(Vendor, id=pk)
    instance.delete()
    return redirect(reverse('vendors:list'))


@method_decorator(staff_member_required, name='dispatch')
class VendorNotesView(ListView):
    template_name = 'vendors/NoteContainer.html'
    model = Note
    
    def get_queryset(self):
        self.vendor = get_object_or_404(Vendor, id=self.kwargs['pk'])
        return self.vendor.notes.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Σημειώσεις {self.vendor}'
        context['back_url'] = self.vendor.get_edit_url()
        context['form'] = NoteForm(initial={'vendor_related': self.vendor})
        context['vendor'] = self.vendor
        return context


@method_decorator(staff_member_required, name='dispatch')
class NoteUpdateView(UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'vendors/note_update.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['vendor_related'] = self.object.vendor_related
        return initial

    def get_success_url(self):
        vendor = self.object.vendor_related
        return reverse('vendors:notes', kwargs={'pk': vendor.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vendor"] = self.object.vendor_related
        context['back_url'] = self.get_success_url()
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


@staff_member_required
def delete_note_view(request, pk):
    note = get_object_or_404(Note, id=pk)
    note.delete()
    return redirect(reverse('vendors:notes', kwargs={'pk': note.vendor_related.id}))

vendors/templates/categories/card_list.html
{% extends 'dashboard.html' %} {% load render_table from django_tables2 %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <button class="btn btn-primary"
                                type="button"
                                data-toggle="collapse"
                                data-target="#filters"
                                aria-expanded="false"
                                aria-controls="collapseExample"
                        >Filters
                        </button>
                         <a href="{% url 'vendors:category_list' %}" class="btn btn-warning pull-right" style="display: inline">Επιστροφη</a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="filters">
                            <form class="form" method="get">
                             <div class="row">
                                 <div class="col-6">
                                     <div class="form-group">
                                         <label for="searchField">Αναζητηση</label>
                                         <input
                                                 type="text"
                                                 class="form-control"
                                                 id="searchField"
                                                 name="search_name"
                                                 placeholder="Πληκρολογήστε..."
                                                 {% if request.GET.search_name %}
                                                    value="{{ request.GET.search_name }}"
                                                 {% endif %}
                                         >
                                     </div>
                                 </div>
                                <div class="col-6">

                                </div>
                                 <div class="col-12">
                                    <h4>Προμηθευτές</h4>

                                    <div class="row">
                                         {% for vendor in vendors %}
                                             <div class="col-3">
                                                 <div class="form-group">
                                                    <input
                                                            name="vendor_name"
                                                            class="form-check-input"
                                                            type="checkbox"
                                                            value="{{ vendor.id }}"
                                                            id="vendor_{{ vendor.id }}"
                                                            {% if vendor.id|stringformat:'s' in request.GET.vendor_name %} checked {% endif %}
                                                    >
                                                    <label class="form-check-label" for="vendor_{{ vendor.id }}">
                                                        {{ vendor }}
                                                    </label>
                                                 </div>
                                             </div>
                                         {% endfor %}
                                    </div>
                                 </div>
                                 <div class="col-6">
                                     <h4>Υποκατηγοριες</h4>
                                     {% for cate in category.get_childrens.all %}
                                        <div class="form-group align-items-center">
                                            <input
                                                    name="cate_name"
                                                    class="form-check-input"
                                                    type="checkbox"
                                                    value="{{ cate.id }}"
                                                    id="cate_{{ cate.id }}"
                                                    {% if cate.id|stringformat:'s' in request.GET.cate_name %} checked {% endif %}
                                            >
                                            <label class="form-check-label" for="cate_{{ cate.id }}">
                                                {{ cate }}
                                            </label>
                                        </div>
                                     {% endfor %}
                                 </div>
                                <button type="submit" class="btn btn-success align-self-center"><i class="fa fa-save"></i> </button>
                             </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Προϊόντα</h6>
                    </div>
                    <div class="card-body">
                        {% render_table queryset_table %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="modal_area"></div>

{% endblock %}

{% block extra_js %}
    <script>
        $('.quick-view').click(function (evt) {
            evt.preventDefault();
            $('#modal_area').empty();
            const myBtn = $(this);
            const url = myBtn.attr('data-href');
            $.ajax({
                method: 'GET',
                url: url,
                dataType: 'json',

                success: function (data) {
                    $('#modal_area').html(data.result);
                    $('#quick_view_modal').modal('show');
                }
            })
        })
    </script>
{% endblock %}